#!/usr/bin/perl

use strict;
use warnings;

use lib qw( /usr/lib/nagios/plugins );
use utils qw(%ERRORS $TIMEOUT &print_revision &support &usage);

my $statuscode = `env http_proxy=http://pazu-lxc:3128 wget --spider -S "www.google.com" 2>&1 | grep "HTTP/" | awk '{print \$2}'`;
chomp($statuscode);

if ($statuscode == "200") {
	my $connections = `netstat -nat | grep :3128 | grep ESTABLISHED| wc -l`;
	chomp($connections);
	if ($connections < 250) {
		print "SQUID OK - current connections: ".$connections."|connections=".$connections.";";
		exit $ERRORS{'OK'};
	} else {
		print "SQUID WARNING - current connections: ".$connections."|connections=".$connections.";";
		exit $ERRORS{'WARNING'};
	}	
} else {
	print "SQUID CRITICAL - Status Code ".$statuscode;
	exit $ERRORS{'CRITICAL'};
}
